### PR TITLE
Rewrite of transaction logging again to support modded containers and moving shulker boxes

### PR DESCRIPTION
**Pull request by konsolas**
- Moved actual logic for logging contains to ServerPlayNetworkHandler to guarantee that we see all window clicks
- Accept `NamedScreenHandlerFactory` implementations that are not subclasses of `LockableContainerBlockEntity`
- Mixin to `deserializeInventory` and `serializeInventory` to persist the container UUID when a shulker box is converted into an item and vice versa
- Commit changes to db when closing inventories, clicking on another inventory, or disconnecting to ensure consistency.

### CODE REVIEW

**Comment by konsolas** [comment]
Artefacts available here for testing: https://github.com/fabricservertools/DeltaLogger/suites/2143357451/artifacts/43847305

**Review by yitzy299 — APPROVED** [review]
Looks good, would like a second pair of eyes from @PotatoPresident

**Review by PotatoPresident — COMMENTED** [review]
Read over it all. All makes sense to me

**Comment by yitzy299** [comment]
Ok great

**Comment by Binero** [comment]
I tested this. It seems like the same containers that were affected before are still affected. As for shulkers, they too lose their transaction history when moved. The original location and the new location will not show the transaction history.

**Comment by konsolas** [comment]
Was `expandedstorage:diamond_chest` one of the containers that didn't log? Those are definitely working for me - 

image

**Comment by konsolas** [comment]
as are shulkers for that matter - 

image

(clearly the transaction occurred before the box was placed at this location in this example)

**Comment by Binero** [comment]
Weirdly enough, diamond chests work for me. Iron chests don't seem to. I will test shulkers too in a bit.
image

**Comment by Binero** [comment]
Never mind, I figured out the issue for the chests. If you put something in it, and take out out without closing the UI, it doesn't log the transaction.

**Comment by konsolas** [comment]
> Never mind, I figured out the issue for the chests. If you put something in it, and take it out without closing the UI, it doesn't log the transaction.

This is intended behaviour. Deltalogger compresses transactions to save storage space.

**Comment by Binero** [comment]
Yup, understandable. Still doesn't explain every behaviour I experienced, but I am first off to eat something before I will test all the blocks again.

**Comment by Binero** [comment]
After another round of testing I can only conclude that the original list of broken containers is still accurate. The Expanded Storage chests indeed log fine, but only if they're not double chests.

I got Shulkers to work once, but tested a dozen times after and could not reproduce it. I can still find the transactions when I do `/dl search`, but that doesn't show which container was modified. That doesn't fix the shulkers not working.

**Pull request merged**
