### PR TITLE
Add ca_CA

### PR DESCRIPTION
**Pull request by Samernieve**
New file for Catalan language

### CODE REVIEW

**Comment by yitzy299** [comment]
Hey sorry, I've just done some refactoring on my local machine, It'll require some translation changes, but I'll keep this open for now.

**Comment by Samernieve** [comment]
Ok, no problem. Great work btw!

**Comment by yitzy299** [comment]
Take a look at the new translations, `en_gb.json` is a good example

**Comment by Samernieve** [comment]
Fixed, ty

**Pull request merged**
